version: "3.7"

services:
  fast-api:
    image: fast-api
    build:
      args:
        dockerfile: ./DockerFile
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
    volumes:
      - ./app:/app